name: just_pdf
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^9.2.0
  auto_route_generator: ^9.0.0
  get_it: ^7.7.0
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  file_picker: ^8.0.5
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_pdfview: ^1.3.2
  printing: ^5.12.0
  url_launcher: ^6.3.0
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  uuid: ^4.4.0
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/png/android/